import * as Linking from 'expo-linking';
import { Platform } from 'react-native';

export type AuthIntent = 'guest' | 'host';

function normalizeIntent(intent?: string): AuthIntent {
  return intent === 'host' ? 'host' : 'guest';
}

/**
 * Builds the approved return address Supabase uses after an email action.
 * Native builds use K9 Country's stable custom URL scheme; web keeps the
 * local/hosted URL generated by Expo Router.
 */
export function getAuthEmailRedirectUrl(intent?: string) {
  const queryParams = { intent: normalizeIntent(intent) };

  if (Platform.OS !== 'web') {
    return Linking.createURL('auth/callback', { queryParams, scheme: 'k9country' });
  }

  return Linking.createURL('auth/callback', { queryParams });
}
